### ISSUE TITLE
This is awesome 

### ISSUE THREAD

**Issue by samoshin** [sulphuris/sulphuris#52]
How long have you been working on this for?

**Comment by stamat** [comment]
@samoshin dude!!!! ❤️  Took me one weekend to write it (to be precise Feb 8th - Feb 10th) Took me more to make it auto publish on NPM registry! 😆 

The main idea is to have powerful generalized CSS code generators and one centralised config file that you can swap per project. Then on compile - strip all the unused CSS and it's 🚀 .

Check out those nested grids https://sulphuris.github.io/sulphuris/

It's far from ready, it needs yet to be documented and there are some advancements I'm planning. It will get even better 🤫  

Sulphur + Mercury + Salt = Philosopher's Stone 😉  Huge appetite, so little time...

**Comment by samoshin** [comment]
Badass dude, gotta keep the side hustles alive.  I'm following this repo now 👀 looking forward to your next release :)
